(function(){
'use strict';let context,master,volume=.22,enabled=false,voiceId='',speaking=false,lastSpeech='',voices=[],generation=0;const active=new Set();
function report(s){window.dispatchEvent(new CustomEvent('audio-status',{detail:s}));}
async function init(){try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC){report('Áudio indisponível neste navegador. Use os rótulos e demonstrações visuais.');return false;}if(!context){context=new AC();master=context.createGain();master.gain.value=volume;master.connect(context.destination);}if(context.state==='suspended')await context.resume();return context.state==='running';}catch(e){report('Não foi possível iniciar o som. Tente “Testar som” após um clique.');return false;}}
async function play(midis,melodic=false,duration=.65){const token=generation;if(!await init()||token!==generation)return;const now=context.currentTime+.02;midis.forEach((m,i)=>{const start=now+(melodic?i*(duration+.08):0),osc=context.createOscillator(),gain=context.createGain();osc.type='triangle';osc.frequency.value=440*Math.pow(2,(m-69)/12);gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(.33/Math.sqrt(melodic?1:midis.length),start+.015);gain.gain.exponentialRampToValueAtTime(.09,start+.18);gain.gain.linearRampToValueAtTime(0,start+duration);osc.connect(gain);gain.connect(master);osc.start(start);osc.stop(start+duration+.03);const node={osc,gain};active.add(node);osc.onended=()=>{active.delete(node);osc.disconnect();gain.disconnect();};});}
function stop(){generation++;active.forEach(({osc,gain})=>{try{gain.gain.cancelScheduledValues(context.currentTime);gain.gain.setTargetAtTime(0,context.currentTime,.008);osc.stop(context.currentTime+.04);}catch(_){}});if('speechSynthesis'in window)window.speechSynthesis.cancel();speaking=false;}
function loadVoices(){if(!('speechSynthesis'in window))return;voices=speechSynthesis.getVoices().sort((a,b)=>(b.lang.toLowerCase()==='pt-br')-(a.lang.toLowerCase()==='pt-br')||b.lang.startsWith('pt')-a.lang.startsWith('pt')||Number(b.localService)-Number(a.localService));window.dispatchEvent(new CustomEvent('voices-ready'));}
function say(text,force=false){lastSpeech=text;if(!enabled&&!force)return;if(!('speechSynthesis'in window)){report('Narração indisponível. Todas as falas estão escritas na cena.');return;}if(speaking||speechSynthesis.speaking||speechSynthesis.pending){report('A fala atual está em andamento. Aguarde ou use “Parar áudio”.');return;}const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';u.rate=.94;u.volume=volume;u.voice=voices.find(v=>v.voiceURI===voiceId)||voices.find(v=>v.lang.toLowerCase()==='pt-br')||voices.find(v=>v.lang.startsWith('pt'))||null;u.onstart=()=>speaking=true;u.onend=()=>speaking=false;u.onerror=e=>{speaking=false;if(!['interrupted','canceled'].includes(e.error))report('A voz não pôde reproduzir a fala. As legendas permanecem disponíveis.');};speaking=true;speechSynthesis.speak(u);}
if('speechSynthesis'in window){speechSynthesis.addEventListener('voiceschanged',loadVoices);loadVoices();}
async function percussion(){const token=generation;if(!await init()||token!==generation)return;const osc=context.createOscillator(),gain=context.createGain(),now=context.currentTime;osc.frequency.setValueAtTime(140,now);osc.frequency.exponentialRampToValueAtTime(42,now+.18);gain.gain.setValueAtTime(.5,now);gain.gain.exponentialRampToValueAtTime(.001,now+.3);osc.connect(gain);gain.connect(master);osc.start();osc.stop(now+.31);const node={osc,gain};active.add(node);osc.onended=()=>{active.delete(node);osc.disconnect();gain.disconnect();};}
window.Sound={init,play,stop,percussion,say,loadVoices,voices:()=>voices,repeat:()=>{if(lastSpeech)say(lastSpeech,true);else report('Entrem em uma cena para ouvir e repetir sua fala.');},setVoice:v=>voiceId=v,setEnabled:v=>{enabled=v;if(!v&&'speechSynthesis'in window){speechSynthesis.cancel();speaking=false;}},setVolume:v=>{volume=v;if(master)master.gain.setTargetAtTime(v,context.currentTime,.03);}};
})();
