/* Conteúdo autoral. Em cada missão: investigação, exemplos, quatro desafios e aplicação. */
(function(){
const K=(title,prompt,pair,explanation)=>({type:'piano',title,prompt,pair,explanation,hints:['Observe a origem, o destino e a grafia indicada.','Inclua a origem na contagem dos nomes. Conte separadamente cada passo cromático.','Carregue a demonstração, acompanhe os marcadores 1 e 2 e reproduza o par.']});
const Q=(title,prompt,options,correct,reasons,pair)=>({type:'question',title,prompt,options,correct,reasons,pair,hints:['Observe qual conceito está sendo solicitado: altura, número, semitons ou qualidade.','Escreva os nomes incluindo a origem; depois conte os passos no piano.','Compare a demonstração com o enunciado e revise a alternativa.']});
window.Missions=[
{title:'Escutar e explorar alturas',room:'Sala de escuta',icon:'◉',achievement:'Distingue altura e intensidade',color:'#8fdcca',intro:'No ensaio, uma melodia parece subir. Será que tocar mais forte faz uma nota ficar mais aguda?',lina:'Uma nota suave também pode ser aguda. Vamos comparar mantendo o volume.',caio:'Vou tocar dó4 e dó5. O que muda na relação entre os sons?',lesson:'Altura distingue sons graves e agudos; intensidade distingue sons mais suaves e mais fortes. No piano, seguir para a direita aumenta a frequência. O número junto ao nome indica a oitava, não a intensidade. Nono ano, escutem primeiro os exemplos e usem os rótulos quando precisarem.',example:['C4','C5'],exampleText:'Dó4 → dó5: a segunda nota tem o dobro da frequência da primeira. Oito nomes são contados: dó, ré, mi, fá, sol, lá, si, dó. Há 12 passos de semitom. É uma oitava justa. Agora comparem dó4 → ré4: a subida é menor.',comparison:['C4','D4'],animation:'chromatic',application:'Escolham dois pares no piano: uma subida pequena e uma maior. Descrevam a diferença entre altura e intensidade sem usar “alto” como sinônimo das duas.',tasks:[
K('Uma subida no estúdio','Selecione dó4 como origem e sol4 como destino. Escute as notas separadas e depois em sequência.',['C4','G4'],'Dó4 é mais grave que sol4. A frequência cresce; aumentar o volume não altera essa relação.'),
Q('O fone do ensaio','Uma pessoa aumenta o volume de dó4 e afirma que a nota virou dó5. Qual análise resolve a dúvida?',['O volume transforma qualquer nota em oitava.','Intensidade e altura são a mesma propriedade.','A nota continua dó4: mudou a intensidade, não a altura.','Dó5 é sempre mais forte que dó4.','A posição da tecla determina apenas o volume.'],2,['Volume não muda a frequência.','São propriedades diferentes.','A frequência define a altura; o volume modifica a intensidade.','Uma nota aguda pode ser tocada suavemente.','A posição corresponde à altura sonora.'],['C4','C5']),
K('Compare uma subida curta','Selecione mi4 → fá4. Ouça e compare com dó4 → dó5 no exemplo. O apoio visual mostra as posições.',['E4','F4'],'Mi4 → fá4 é uma subida de um semitom. Duas teclas brancas vizinhas também podem estar muito próximas.'),
Q('Leitura de um esquema','No esquema dó4 → sol4 → dó5, com volume constante, qual afirmação está correta?',['As alturas sobem, mesmo sem aumentar a intensidade.','Todas têm a mesma altura por usarem o mesmo volume.','A nota mais à direita é necessariamente mais forte.','A seta representa duração, sem relação com altura.','Dó4 e dó5 são a mesma altura porque têm o mesmo nome.'],0,['A posição e a frequência aumentam nessa sequência.','Volume constante não implica frequência constante.','Intensidade pode ser ajustada independentemente.','Aqui a seta ordena as alturas.','O nome se repete, mas a oitava muda a frequência.'],['C4','C5'])]},
{title:'Descobrir tons e semitons',room:'Oficina cromática',icon:'⌁',achievement:'Reconhece semitons',color:'#e9c57b',intro:'A equipe conta teclas brancas e supõe que toda distância entre vizinhas é igual. O piano confirma essa hipótese?',lina:'Entre mi e fá não há tecla preta. Entre dó e ré há.',caio:'Vamos contar os espaços percorridos, e não o total de teclas.',lesson:'Semitom é o menor passo entre alturas vizinhas deste piano temperado. Um tom corresponde a dois semitons. Mi–fá e si–dó são semitons naturais. Dó–ré, ré–mi, fá–sol, sol–lá e lá–si são tons. Duas teclas brancas consecutivas podem estar a um tom ou a um semitom.',example:['E4','F4'],exampleText:'Mi4 → fá4: mi é a origem (zero passos). Chegar a fá soma um passo: 1 semitom. Dó4 → ré4 passa por dó♯4 e chega a ré4: 2 passos, ou 1 tom. Não conte a tecla inicial como um passo.',comparison:['C4','D4'],animation:'chromatic',application:'Encontrem e registrem um semitom natural e um tom no piano. Expliquem por que contar apenas teclas brancas não mede a distância sonora.',tasks:[
K('Semitom natural','Construa mi4 → fá4. As duas teclas são brancas, e a distância é um semitom.',['E4','F4'],'Não há altura intermediária neste teclado: mi4 → fá4 é um único passo cromático.'),
Q('A régua do compositor','Um arranjo pede subir um tom a partir de dó4. Qual percurso atende à instrução?',['Dó4 → dó♯4: um passo.','Dó4 → ré4: dois semitons.','Dó4 → mi4: quatro semitons.','Dó4 → fá4: cinco semitons.','Permanecer em dó4 e aumentar o volume.'],1,['Um passo é semitom, metade de um tom.','Dó → dó♯ → ré percorre dois passos: um tom.','Quatro semitons correspondem a dois tons.','Cinco semitons não são um tom.','Mudar intensidade não transpõe a nota.'],['C4','D4']),
K('Na virada da oitava','Selecione si4 → dó5. Compare com mi4 → fá4: ambos têm um semitom.',['B4','C5'],'A mudança de oitava não significa sempre uma distância de oitava. Si4 → dó5 é um passo e uma segunda menor.'),
Q('Uma hipótese a revisar','Qual afirmação sobre o teclado está incorreta?',['Um tom equivale a dois semitons.','Mi–fá é um semitom natural.','Si4–dó5 é um semitom natural.','Toda dupla de teclas brancas consecutivas está a um tom.','Dó–ré passa por uma tecla preta.'],3,['Essa equivalência está correta.','Não há tecla entre mi e fá.','Não há tecla entre si e dó.','Mi–fá e si–dó são contraexemplos: um semitom.','Dó♯/ré♭ está entre dó e ré.'],['E4','F4'])]},
{title:'Contar os nomes das notas',room:'Mesa de partitura',icon:'≡',achievement:'Constrói uma quarta',color:'#a9a5ee',intro:'Uma partitura liga dó a fá. Alguém contou só ré, mi e fá e chamou o intervalo de terça. O que ficou de fora?',lina:'A origem também participa da contagem dos nomes.',caio:'Quatro nomes e cinco semitons: são duas medidas distintas.',lesson:'O número do intervalo vem da contagem inclusiva dos nomes diatônicos, da origem ao destino. Alterações não acrescentam nomes: fá e fá♯ ocupam o lugar de fá nessa contagem. Uníssono, segunda, terça, quarta, quinta, sexta, sétima e oitava são os números possíveis aqui. Primeiro conte os nomes; depois meça a distância sonora.',example:['C4','F4'],exampleText:'Dó4 → fá4: dó (1), ré (2), mi (3), fá (4). Número: quarta. O percurso cromático tem 5 passos, por isso é quarta justa. A contagem dos quatro nomes não é uma contagem de quatro semitons.',comparison:['C4','G4'],animation:'names',application:'Escolham um par com origem diferente de dó. Escrevam todos os nomes da contagem, incluindo origem e destino, e registrem seu número.',tasks:[
K('Construa uma quarta','No piano, selecione dó4 → fá4 e acompanhe a contagem inclusiva dos nomes.',['C4','F4'],'Dó, ré, mi, fá: quatro nomes. Cinco semitons: quarta justa.'),
Q('A anotação do ensaio','Uma estudante registrou dó–fá como terça por contar ré, mi e fá. Qual correção deve fazer?',['Trocar fá por fá♯ para obter quatro nomes.','Contar só as teclas pretas.','Incluir dó: dó, ré, mi, fá, uma quarta.','Chamar de quinta porque há cinco semitons.','Aumentar o volume para incluir a origem.'],2,['A alteração muda altura, mas não o nome diatônico.','Teclas pretas não definem o número.','A contagem é inclusiva e resulta em quatro nomes.','Semitons e número do intervalo são medidas diferentes.','Volume não interfere nessa contagem.'],['C4','F4']),
K('Outra origem, mesma lógica','Selecione ré4 → sol4. Conte ré, mi, fá, sol, incluindo a origem.',['D4','G4'],'Ré, mi, fá, sol são quatro nomes; cinco semitons dão quarta justa, também a partir de ré.'),
Q('O esquema da melodia','Uma melodia sobe de mi4 para si4. Contando mi, fá, sol, lá, si, o número é:',['quarta, pois a origem não entra.','quinta, pois são cinco nomes.','sétima, pois são sete semitons.','segunda, pois apenas duas notas são tocadas.','oitava, pois a melodia sobe.'],1,['A origem precisa entrar na contagem.','Cinco nomes resultam em quinta; a distância é sete semitons.','Sete semitons não significam sete nomes.','Os nomes intermediários contam mesmo sem serem tocados.','Uma subida pode ter vários tamanhos.'],['E4','B4'])]},
{title:'Identificar intervalos e qualidades',room:'Laboratório de relações',icon:'◇',achievement:'Relaciona número e qualidade',color:'#e6a4bb',intro:'Duas terças podem ter tamanhos sonoros diferentes. Como escrever uma descrição completa?',lina:'Número primeiro, semitons depois. Só então escolhemos a qualidade.',caio:'Dó–mi♭ e dó–mi são terças, mas não têm a mesma distância.',lesson:'A referência é: uníssono justo 0; segunda maior 2; terça maior 4; quarta justa 5; quinta justa 7; sexta maior 9; sétima maior 11; oitava justa 12 semitons. Segundas, terças, sextas e sétimas ficam menores com um semitom a menos. Uníssono, quarta, quinta e oitava pertencem à família justa. Um semitom acima da referência dá aumentada; na família justa, um abaixo dá diminuta. Na família maior, dois abaixo da maior dão diminuta.',example:['C4','Eb4'],exampleText:'Dó4 → mi♭4: dó, ré, mi = terça. Dó → dó♯ → ré → ré♯/mi♭ = 3 semitons. A terça maior tem 4; um a menos dá terça menor. Dó4 → mi4 conserva três nomes, mas tem 4 semitons: terça maior.',comparison:['C4','E4'],animation:'chromatic',application:'Construam uma terça menor e uma maior, com a mesma origem. Registrem o que se conserva e o que muda na grafia e no som.',tasks:[
K('Uma terça menor','Use a grafia em bemóis e selecione dó4 → mi♭4.',['C4','Eb4'],'Dó, ré, mi = terça; três semitons = terça menor. Ré♯ soaria igual, mas teria outro número.'),
Q('A escolha no arranjo','A partitura pede dó4–sol4. Qual análise completa atende à escrita?',['Quinta justa: cinco nomes e sete semitons.','Sétima maior: sete semitons.','Quarta justa: ignorando a origem.','Quinta menor: toda quinta é maior ou menor.','Quinta aumentada: sete semitons.'],0,['Dó, ré, mi, fá, sol: quinta; sete semitons: justa.','Número não é quantidade de semitons.','Ignorar a origem produz uma contagem incorreta.','Quintas pertencem à família justa.','A quinta aumentada teria oito semitons.'],['C4','G4']),
K('A terça maior de outra origem','Selecione fá4 → lá4. Conte fá, sol, lá e quatro semitons.',['F4','A4'],'Três nomes e quatro semitons: terça maior. A lógica não depende de começar em dó.'),
Q('Completar uma análise','Ré4–fá4 conta ré, mi, fá e percorre três semitons. Qual conclusão segue desses dados?',['Segunda maior.','Terça maior.','Terça menor.','Quarta diminuta.','Uníssono aumentado.'],2,['São três nomes, não dois.','Uma terça maior tem quatro semitons.','Três nomes e três semitons definem terça menor.','Uma quarta exigiria quatro nomes.','Um uníssono conserva o nome diatônico.'],['D4','F4'])]},
{title:'Investigar som e grafia',room:'Cabine de enarmonia',icon:'⇄',achievement:'Explica a grafia do intervalo',color:'#7dc9ee',intro:'Dois arranjos usam a mesma tecla preta: um escreve fá♯, outro sol♭. O som basta para nomear o intervalo?',lina:'No temperamento igual, fá♯ e sol♭ compartilham altura. A escrita ainda importa.',caio:'Vamos comparar dó–fá♯ e dó–sol♭ sem apagar os nomes.',lesson:'Enarmonia é a relação entre grafias diferentes que correspondem à mesma altura no temperamento igual. Dó–fá♯ conta quatro nomes e tem 6 semitons: quarta aumentada. Dó–sol♭ conta cinco nomes e tem os mesmos 6 semitons: quinta diminuta. Ouvir seis semitons identifica a distância, mas não determina a grafia nem o nome completo.',example:['C4','F#4'],exampleText:'Dó, ré, mi, fá = quarta. A quarta justa tem 5 semitons; com fá♯ são 6: quarta aumentada. Compare dó, ré, mi, fá, sol = quinta. A quinta justa tem 7 semitons; com sol♭ são 6: quinta diminuta.',comparison:['C4','Gb4'],animation:'enharmonic',application:'Justifiquem para uma pessoa do ensaio por que seis semitons não bastam para decidir entre quarta aumentada e quinta diminuta. Usem as duas contagens.',tasks:[
K('A grafia com sustenido','Selecione dó4 → fá♯4, com grafia em sustenidos.',['C4','F#4'],'Quatro nomes e seis semitons: quarta aumentada. A tecla compartilhada mantém a grafia solicitada.'),
Q('Duas partituras, uma altura','Um arquivo escreve dó–fá♯ e outro dó–sol♭. No temperamento igual, qual análise é adequada?',['Ambos são quarta aumentada porque soam iguais.','Ambos são quinta diminuta porque usam tecla preta.','O primeiro é quarta aumentada, o segundo quinta diminuta; ambos têm seis semitons.','O primeiro tem cinco semitons e o segundo sete.','A grafia não participa da análise.'],2,['O som não informa sozinho o número diatônico.','Uma tecla preta pode ter grafias diferentes.','O número vem dos nomes; a distância sonora é igual nesses dois pares.','Cinco e sete são as referências justas, não esses pares alterados.','Sem a grafia, a classificação completa é ambígua.'],['C4','F#4']),
K('A mesma tecla, outra escrita','Mude para bemóis e selecione dó4 → sol♭4. A tecla de destino é a mesma de fá♯4.',['C4','Gb4'],'Cinco nomes e seis semitons: quinta diminuta. O som é igual ao anterior no temperamento igual.'),
Q('Análise de um argumento','Uma pessoa diz: “Reconheci seis semitons, logo o intervalo só pode ser quarta aumentada.” Qual resposta é mais rigorosa?',['Concordar: semitons bastam para qualquer classificação.','Concordar: toda tecla preta é sustenido.','Discordar: seis semitons não podem existir.','Pedir a grafia: dó–sol♭ seria quinta diminuta com essa mesma distância.','Aumentar o volume para descobrir o nome.'],3,['É preciso o número diatônico.','A tecla admite grafias como fá♯ e sol♭.','Seis semitons formam uma distância possível.','A grafia permite distinguir os nomes do intervalo.','Intensidade não revela o nome diatônico.'],['C4','Gb4'])]},
{title:'Resolver, revisar e criar',room:'Palco de autoria',icon:'✦',achievement:'Investiga e cria com intervalos',color:'#e9c57b',intro:'Chegou a sessão de gravação. Nono ano, usem as descobertas para analisar argumentos, resolver uma prova e criar uma ideia musical.',lina:'Na prova, podemos navegar e revisar antes de finalizar.',caio:'Na composição, cada relação entre sons pode ser uma escolha expressiva.',lesson:'Organizem cada análise em três etapas: nomes inclusivos → número; passos cromáticos → semitons; comparação com a referência → qualidade. Ao transpor um pequeno exemplo, preservem sua distância e sua grafia diatônica. A prova tem oito questões autorais, sem limite de tempo; a correção aparece somente ao finalizar.',example:['D4','G4'],exampleText:'Transpor dó4–fá4 um tom acima leva a ré4–sol4. Nos dois casos são quatro nomes e cinco semitons: quarta justa. Trocar apenas o destino não garante a preservação do intervalo.',comparison:['C4','F4'],animation:'names',application:'Escrevam uma estratégia para resolver uma questão de intervalos: como vocês verificariam número, semitons e qualidade? Depois façam a prova e criem sua sequência.',tasks:[
K('Transpor uma quarta','O motivo dó4–fá4 foi transposto um tom acima. Construa ré4 → sol4.',['D4','G4'],'A transposição preserva a quarta justa: ré, mi, fá, sol e cinco semitons.'),
Q('Argumento para a prova','Para verificar dó–fá♯, qual procedimento é adequado?',['Contar apenas seis semitons e chamar de sexta.','Contar quatro nomes, medir seis semitons e comparar com os cinco da quarta justa.','Contar as teclas brancas e ignorar a alteração.','Escolher quinta diminuta só pelo som.','Medir o volume das duas notas.'],1,['Seis semitons não definem o número sexta.','Quarta com um semitom acima da justa: aumentada.','Ignorar a alteração perde a distância sonora.','Quinta diminuta exigiria grafia até sol.','Volume não classifica intervalos.'],['C4','F#4']),
K('Escolha para a criação','Construa sol4 → si♭4 em bemóis. Essa terça menor poderá entrar na sua sequência.',['G4','Bb4'],'Sol, lá, si = terça; três semitons = terça menor.'),
Q('Revisar uma escolha','Uma sequência contém lá4 → dó5. A análise conta lá, si, dó e três semitons. Qual justificativa funciona?',['É oitava porque o número da oitava mudou.','É segunda porque apenas duas notas foram tocadas.','É terça maior porque há três nomes.','É terça menor: três nomes e três semitons.','É quarta justa porque dó é tecla branca.'],3,['Cruzar a numeração de oitava não define uma oitava musical.','Os nomes intermediários participam da contagem.','A qualidade maior precisaria de quatro semitons.','A contagem inclusiva e a distância sustentam a terça menor.','A cor da tecla não define a qualidade.'],['A4','C5'])]}
];
/* Dois conjuntos progressivos. A ordem das alternativas também varia a cada tentativa. */
window.ExamSets=[[
Q('Altura e intensidade','Num ensaio, ré4 é tocado com mais volume. O que mudou?',['A intensidade.','A altura virou ré5.','O nome virou mi.','A distância virou um tom.','A oitava mudou.'],0,['Volume modifica intensidade.','A frequência de ré4 permanece.','Volume não troca o nome.','É preciso outra altura para medir distância.','A oitava depende da altura.'],['D4','D4']),
Q('Semitons naturais','Qual par tem um semitom natural?',['Dó4–ré4.','Fá4–sol4.','Lá4–si4.','Mi4–fá4.','Ré4–mi4.'],3,['Dois semitons.','Dois semitons.','Dois semitons.','Um passo sem altura intermediária.','Dois semitons.'],['E4','F4']),
Q('Contagem inclusiva','Uma partitura liga ré4 a lá4. Qual é o número do intervalo?',['Quarta.','Quinta.','Sétima.','Segunda.','Oitava.'],1,['Exclui indevidamente a origem.','Ré, mi, fá, sol, lá: cinco nomes.','Confunde os sete semitons com os nomes.','Conta só as notas tocadas.','Não há oito nomes.'],['D4','A4']),
Q('Qualidade da terça','Um motivo usa fá4–lá♭4, três nomes e três semitons. O intervalo é:',['Terça maior.','Segunda aumentada.','Terça menor.','Quarta justa.','Quinta diminuta.'],2,['Terça maior tem quatro semitons.','Segunda exigiria dois nomes.','Três nomes e três semitons: terça menor.','Quarta exigiria quatro nomes e cinco semitons para ser justa.','Quinta exigiria cinco nomes.'],['F4','Ab4']),
Q('Família justa','Dó4–sol4 tem cinco nomes e sete semitons. Como classificar?',['Quinta justa.','Quinta menor.','Sétima maior.','Quarta aumentada.','Quinta aumentada.'],0,['É a referência da quinta justa.','Quintas pertencem à família justa.','Número não é distância cromática.','Exigiria quatro nomes e seis semitons.','Uma quinta aumentada tem oito semitons.'],['C4','G4']),
Q('Som e escrita','Uma partitura escreve dó4–sol♭4. São seis semitons. Qual intervalo está escrito?',['Quarta aumentada.','Quinta justa.','Sexta menor.','Quinta diminuta.','Terça menor.'],3,['Essa grafia terminaria em fá♯.','A quinta justa tem sete semitons.','São cinco nomes, não seis.','Cinco nomes e um semitom abaixo da quinta justa.','Não são três nomes.'],['C4','Gb4']),
Q('Transposição','O exemplo dó4–mi4 sobe um tom inteiro. Qual par preserva a terça maior?',['Ré4–fá4.','Ré4–fá♯4.','Ré4–sol4.','Dó♯4–mi4.','Ré4–mi4.'],1,['Três semitons: terça menor.','Ambas as notas subiram dois semitons; três nomes e quatro semitons.','É uma quarta justa.','As duas notas não subiram igualmente.','É segunda maior.'],['D4','F#4']),
Q('Análise de argumentos','Um áudio isolado revela seis semitons. Qual conclusão é justificada?',['É necessariamente quarta aumentada.','É necessariamente quinta diminuta.','A intensidade revela a grafia.','A origem deve ser dó.','A distância está identificada; o nome completo exige a grafia.'],4,['Pode ser quinta diminuta em outra grafia.','Pode ser quarta aumentada em outra grafia.','Intensidade não determina a escrita.','Várias origens permitem seis semitons.','Som informa distância; escrita permite contar nomes.'],['C4','F#4'])
],[
Q('Altura e intensidade','No estúdio, lá4 e lá5 são tocados com o mesmo volume. Qual relação permanece?',['Têm a mesma frequência.','Lá5 é mais agudo, mesmo com a mesma intensidade.','Lá5 é necessariamente mais forte.','São um uníssono justo.','Volume igual elimina a oitava.'],1,['Lá5 tem o dobro da frequência de lá4.','Altura e intensidade são independentes.','Volume pode ser igual.','A oitava é diferente.','Volume não altera a distância sonora.'],['A4','A5']),
Q('Semitom na oitava','Si4–dó5 é usado num motivo. A distância corresponde a:',['Uma oitava.','Um tom.','Dois tons.','Um semitom.','Cinco semitons.'],3,['A mudança do numeral não significa intervalo de oitava.','Um tom tem dois semitons.','Dois tons têm quatro semitons.','Si e dó são vizinhos cromáticos.','Não há cinco passos nesse percurso.'],['B4','C5']),
Q('Contagem inclusiva','Sol4–dó5 conta sol, lá, si, dó. Qual é o número?',['Terça.','Quinta.','Quarta.','Oitava.','Segunda.'],2,['Seria excluir a origem.','São quatro nomes, não cinco.','A contagem inclusiva tem quatro nomes.','Não são oito nomes.','Os nomes intermediários entram na análise.'],['G4','C5']),
Q('Qualidade da terça','Lá4–dó♯5 conta três nomes e quatro semitons. É:',['Terça maior.','Terça menor.','Quarta justa.','Segunda maior.','Quinta justa.'],0,['Três nomes e quatro semitons são a referência maior.','A menor teria três semitons.','Quarta exige quatro nomes.','Segunda exige dois nomes.','Quinta exige cinco nomes.'],['A4','C#5']),
Q('Família justa','Ré4–sol4 conta quatro nomes e cinco semitons. É:',['Quarta maior.','Quinta diminuta.','Terça menor.','Quarta aumentada.','Quarta justa.'],4,['Quarta pertence à família justa.','Quinta exige cinco nomes.','Terça exige três nomes.','Aumentada teria seis semitons.','Quatro nomes e cinco semitons: quarta justa.'],['D4','G4']),
Q('Som e escrita','Ré4–sol♯4 percorre seis semitons. Qual análise corresponde à grafia?',['Quinta diminuta.','Quarta aumentada.','Quarta justa.','Sexta maior.','Quinta justa.'],1,['Essa grafia seria ré–lá♭.','Ré, mi, fá, sol: quarta, com um semitom acima da justa.','Justa teria cinco semitons.','Não são seis nomes nem nove semitons.','Não são cinco nomes nem sete semitons.'],['D4','G#4']),
Q('Transposição','Ré4–fá4 sobe um tom inteiro. Qual par preserva sua terça menor?',['Mi4–sol♯4.','Mi4–fá4.','Ré4–sol4.','Mi4–sol4.','Mi4–lá4.'],3,['É terça maior.','É segunda menor.','É quarta justa.','Ambas sobem dois semitons e preservam três nomes e três semitons.','É quarta justa.'],['E4','G4']),
Q('Análise de argumentos','Dois arranjos usam ré–sol♯ e ré–lá♭. Qual justificativa é correta no temperamento igual?',['Mesmo som: quarta aumentada e quinta diminuta, respectivamente.','São dois nomes para quinta justa.','A segunda grafia tem um semitom a mais.','O volume define qual é quarta.','A escrita pode ser ignorada.'],0,['Quatro e cinco nomes, ambos com seis semitons.','A quinta justa tem sete semitons.','Sol♯ e lá♭ compartilham altura.','Intensidade não define número.','A escrita define a contagem diatônica.'],['D4','Ab4'])
]];
/* Apoio explícito: conceitos abrem piano sob demanda; leituras de intervalos o integram. */
Missions.forEach((m,i)=>m.tasks.forEach(t=>{t.pianoSupport=t.type==='piano'||i>=2?'inline':'optional';}));
window.ExamConcepts=['Altura e intensidade','Tons e semitons','Contagem dos nomes','Terças e qualidades','Família justa','Enarmonia','Transposição','Análise de argumentos'];
window.ExamReview=[1,2,3,4,4,5,6,5];
})();
