(function(){
const shortcuts=['a','w','s','e','d','f','t','g','y','h','u','j','k','o','l','p',';','z','x','c','v','b','n','m',','];
class Piano{
 constructor(host,onSelect){this.host=host;this.onSelect=onSelect;this.onStateChange=null;this.analyzed=false;this.notes=[null,null];this.slot=0;this.spelling='sharp';this.investigateAllowed=false;this.keyHandler=e=>{if(e.ctrlKey||e.altKey||e.metaKey||e.repeat||e.target.closest('input,textarea,select,button,a,[contenteditable]'))return;const i=shortcuts.indexOf(e.key.toLowerCase());if(i>=0){e.preventDefault();this.pick(Music.fromMidi(60+i,this.spelling));}};document.addEventListener('keydown',this.keyHandler);this.render();}
 destroy(){document.removeEventListener('keydown',this.keyHandler);}
 render(){let whites=0,keys='';for(let m=60;m<=84;m++){const black=[1,3,6,8,10].includes(m%12),n=Music.fromMidi(m,this.spelling),other=Music.fromMidi(m,this.spelling==='sharp'?'flat':'sharp');const pos=black?(whites-.31)*100/15:whites*100/15;keys+=`<button type="button" class="key ${black?'black':'white'}" style="left:${pos}%;width:${black?4.13:6.667}%" data-midi="${m}" aria-label="${Music.label(n)}${black?', também '+Music.label(other):''}; atalho ${shortcuts[m-60]}"><span class="key-marker"></span><span class="key-name">${Music.label(n)}${black?'<small>'+Music.label(other)+'</small>':''}</span><kbd>${shortcuts[m-60].toUpperCase()}</kbd></button>`;if(!black)whites++;}
 this.host.innerHTML=`<div class="piano-top"><div><span class="eyebrow">INSTRUMENTO · DÓ4 A DÓ6</span><h2>Seu piano de investigação</h2></div><label>Grafia das teclas pretas <select id="spelling"><option value="sharp" ${this.spelling==='sharp'?'selected':''}>Sustenidos ♯</option><option value="flat" ${this.spelling==='flat'?'selected':''}>Bemóis ♭</option></select></label></div><div class="selection" role="group" aria-label="Ordem das notas"><button data-slot="0" class="origin">① Origem: <span>${this.notes[0]?Music.label(this.notes[0]):'selecionar'}</span></button><span aria-hidden="true">→</span><button data-slot="1" class="destination">② Destino: <span>${this.notes[1]?Music.label(this.notes[1]):'selecionar'}</span></button></div><p class="small" id="piano-order">Clique em ① ou ② para editar essa nota. Teclas do computador indicadas no instrumento; Tab e Enter também funcionam. O segundo dó de cada oitava tem altura diferente.</p><div class="piano-scroll"><div class="keyboard" aria-label="Piano de duas oitavas">${keys}</div></div><div class="piano-controls"><button data-piano="origin">Ouvir ①</button><button data-piano="destination">Ouvir ②</button><button data-piano="melodic">♫ Em sequência</button><button data-piano="harmonic">♬ Simultaneamente</button><button data-piano="repeat">Repetir par</button><button data-piano="clear">Limpar seleção</button><button data-piano="investigate" class="primary">Investigar intervalo</button></div><div id="analysis" role="status" aria-live="polite"></div>`;
 this.host.onclick=e=>{const key=e.target.closest('[data-midi]'),slot=e.target.closest('[data-slot]'),action=e.target.closest('[data-piano]');if(key)this.pick(Music.fromMidi(+key.dataset.midi,this.spelling));if(slot){this.slot=+slot.dataset.slot;this.update();this.changed();}if(action)this.action(action.dataset.piano);};this.host.querySelector('#spelling').onchange=e=>{this.spelling=e.target.value;this.render();this.host.querySelector('#spelling').focus({preventScroll:true});this.changed();};this.update();}
 pick(n){this.notes[this.slot]={...n};this.slot=this.slot===0?1:0;Sound.play([Music.midi(n)]);this.analyzed=false;this.host.querySelector('#analysis').textContent='';this.update();this.onSelect?.(n);this.changed();}
 setPair(pair){this.notes=pair.map(x=>typeof x==='string'?Music.parse(x):{...x});this.slot=0;this.spelling=this.notes.some(n=>n.alteration===-1)?'flat':'sharp';this.analyzed=false;this.render();this.changed();}
 clear(){this.notes=[null,null];this.slot=0;this.update();this.host.querySelector('#analysis').innerHTML='';this.analyzed=false;this.changed();}
 update(){this.host.querySelectorAll('[data-slot]').forEach(b=>{const i=+b.dataset.slot;b.classList.toggle('active-slot',i===this.slot);b.setAttribute('aria-pressed',String(i===this.slot));b.querySelector('span').textContent=this.notes[i]?Music.label(this.notes[i]):'selecionar';});this.host.querySelectorAll('[data-midi]').forEach(b=>{const m=+b.dataset.midi,slots=this.notes.map((n,i)=>n&&Music.midi(n)===m?i+1:null).filter(Boolean);b.classList.toggle('selected-origin',slots.includes(1));b.classList.toggle('selected-destination',slots.includes(2));b.querySelector('.key-marker').textContent=slots.join('·');b.setAttribute('aria-pressed',String(slots.length>0));});this.host.querySelector('[data-piano="investigate"]').disabled=!this.investigateAllowed;}
 action(a){if(a==='clear'){this.clear();return;}if(a==='investigate'){if(this.investigateAllowed)this.investigate();return;}const ns=a==='origin'?[this.notes[0]]:a==='destination'?[this.notes[1]]:this.notes;if(ns.some(n=>!n)){window.dispatchEvent(new CustomEvent('audio-status',{detail:'Selecione as notas necessárias no piano.'}));return;}Sound.play(ns.map(Music.midi),['melodic','repeat'].includes(a));}
 investigate(){if(this.notes.some(n=>!n)){this.host.querySelector('#analysis').textContent='Selecione origem e destino.';return;}this.analyzed=true;const r=Music.analyze(...this.notes);this.host.querySelector('#analysis').innerHTML=r.valid?`<div class="analysis-grid"><div><small>① NOMES CONTADOS</small><strong>${r.number} · ${r.counted.join(' → ')}</strong></div><div><small>② DISTÂNCIA SONORA</small><strong>${r.semitones} semitons</strong></div><div><small>③ NÚMERO + QUALIDADE</small><strong>${r.name}</strong></div></div>`:r.message;this.changed();}
 getState(){return {notes:this.notes.map(n=>n?{...n}:null),slot:this.slot,spelling:this.spelling,analyzed:this.analyzed};}
 restore(saved){if(!saved)return;this.notes=Array.isArray(saved.notes)&&saved.notes.length===2?saved.notes.map(n=>Music.valid(n)&&Music.midi(n)>=60&&Music.midi(n)<=84?{...n}:null):[null,null];this.slot=saved.slot===1?1:0;this.spelling=saved.spelling==='flat'?'flat':'sharp';this.render();if(saved.analyzed&&this.investigateAllowed&&this.notes.every(Boolean))this.investigate();}
 changed(){this.onStateChange?.(this.getState());}
 mark(m){this.host.querySelectorAll('.key').forEach(b=>b.classList.toggle('trace-key',+b.dataset.midi===m));}
}
window.Piano=Piano;
})();
