(function(){
const key='missoes-musicais-v1';
const initial=()=>({version:1,completed:[],records:{},applications:{},examAttempts:[],composition:[],reflection:'',journey:{missionSteps:{},drafts:{},hints:{},hintEvents:{},applicationDrafts:{},resume:null},preferences:{volume:.22,narration:false,voice:'',text:'1',reduced:false,teacher:false,presentation:false}});
let state=initial(),storageOK=true;
try{const s=JSON.parse(localStorage.getItem(key)||'null');if(s&&s.version===1&&Array.isArray(s.completed)&&s.records&&s.preferences)state={...state,...s,preferences:{...state.preferences,...s.preferences},journey:{...state.journey,...s.journey,missionSteps:{...s.journey?.missionSteps},drafts:{...s.journey?.drafts},hints:{...s.journey?.hints},hintEvents:{...s.journey?.hintEvents},applicationDrafts:{...s.journey?.applicationDrafts}}};}catch(_){storageOK=false;}
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch(_){storageOK=false;window.dispatchEvent(new CustomEvent('storage-error'));}}
function record(id,answer,correct,guided=false,context={}){if(!state.records[id])state.records[id]={initial:{answer,correct,time:Date.now(),...context},revisions:[],resolved:correct,guided:false};else{state.records[id].revisions.push({answer,correct,guided,time:Date.now(),...context});state.records[id].resolved||=correct||guided;}state.records[id].guided||=guided;if(guided)state.records[id].resolved=true;save();}
function validateCreation(o){if(!o||o.format!=='missoes-musicais-composicao'||o.version!==1||!Array.isArray(o.notes)||o.notes.length<4||o.notes.length>8||typeof o.reflection!=='string'||o.reflection.length>3000)throw new Error('Use um JSON de composição deste estúdio, com 4 a 8 notas e reflexão de até 3000 caracteres.');if(!o.notes.every(n=>Music.valid(n)&&Music.midi(n)>=60&&Music.midi(n)<=84&&Object.keys(n).every(k=>['letter','alteration','octave'].includes(k))))throw new Error('Há notas inválidas ou fora do piano (dó4 a dó6).');return {notes:o.notes.map(n=>({letter:n.letter,alteration:n.alteration,octave:n.octave})),reflection:o.reflection};}
window.Progress={get state(){return state;},get storageOK(){return storageOK;},save,record,validateCreation,reset:()=>{state=initial();save();}};
})();
