'use strict';
/* Teste de integração por CDP, sem dependências. Node 22+ e Edge/Chrome. */
const fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process'),assert=require('node:assert/strict');
const base=path.resolve(__dirname,'..'),out=path.join(base,'.validation');fs.mkdirSync(out,{recursive:true});
const edge=process.env.BROWSER_PATH||'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe';
const exportedBefore=path.join(out,'minha-sequencia-musical.json');if(fs.existsSync(exportedBefore))fs.unlinkSync(exportedBefore);
const port=9441,profile=path.join(out,'edge-profile-'+Date.now());
const keepalive=setInterval(()=>{},1000);console.log('Iniciando Edge headless...');
const child=spawn(edge,['--headless=new','--disable-gpu','--no-sandbox','--disable-features=RendererCodeIntegrity','--no-first-run','--no-default-browser-check','--remote-debugging-port='+port,'--user-data-dir='+profile,'about:blank'],{stdio:'ignore',windowsHide:true});
let ws,id=0;const pending=new Map(),errors=[],checks=[];const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function cdp(method,params={}){const n=++id;return new Promise((resolve,reject)=>{pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));setTimeout(()=>{if(pending.has(n)){pending.delete(n);reject(Error('Timeout '+method));}},12000).unref();});}
async function evaluate(expression){const r=await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;}
async function check(name,expression){const value=await evaluate(expression);assert.ok(value,name);checks.push(name);console.log('PASS:',name);}
const click=s=>evaluate(`document.querySelector(${JSON.stringify(s)}).click()`);
const change=(s,value)=>evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(s)});el.value=${JSON.stringify(value)};el.dispatchEvent(new Event('change',{bubbles:true}));})()`);
async function shot(name){const s=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,name),Buffer.from(s.data,'base64'));}
async function selectPair(pair){await click('[data-piano="clear"]');for(const name of pair){await evaluate(`(()=>{const n=Music.parse(${JSON.stringify(name)});document.querySelector('[data-midi="'+Music.midi(n)+'"]').click();})()`);}}
async function fileInput(filename){const doc=await cdp('DOM.getDocument');const node=await cdp('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'#import-json'});await cdp('DOM.setFileInputFiles',{nodeId:node.nodeId,files:[filename]});await delay(300);}
(async()=>{try{
let target;for(let n=0;n<60;n++){try{const res=await fetch(`http://127.0.0.1:${port}/json/list`);target=(await res.json()).find(t=>t.type==='page');if(target)break;}catch{}await delay(200);}assert.ok(target,'Edge deve iniciar');
ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});ws.onmessage=ev=>{const msg=JSON.parse(ev.data);if(msg.id){const p=pending.get(msg.id);if(p){pending.delete(msg.id);msg.error?p.reject(Error(msg.error.message)):p.resolve(msg.result);}}else if(msg.method==='Page.javascriptDialogOpening')cdp('Page.handleJavaScriptDialog',{accept:true}).catch(()=>{});else if(msg.method==='Runtime.exceptionThrown')errors.push(msg.params.exceptionDetails.exception?.description||msg.params.exceptionDetails.text);else if(msg.method==='Log.entryAdded'&&msg.params.entry.level==='error')errors.push(msg.params.entry.text);};
console.log('Conectado ao CDP.');await cdp('Runtime.enable');await cdp('Page.enable');await cdp('Log.enable');await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
console.log('Abrindo arquivo local.');await cdp('Page.navigate',{url:'file:///'+path.join(base,'index.html').replaceAll('\\','/')});for(let n=0;n<50;n++){if(await evaluate("!!document.querySelector('h1')"))break;await delay(100);}
﻿await check('Abertura local e barra compacta em fluxo',`document.querySelector('h1').textContent.includes('Musicais')&&getComputedStyle(document.querySelector('#sound-dock')).position==='static'`);
await click('#audio-settings');await check('Preferências expansíveis e seleção de voz',`!document.querySelector('#settings').hidden&&document.querySelector('#voice')`);await click('#voice-test');await click('[data-action="sound-test"]');await click('[data-action="stop-sound"]');await click('#audio-settings');await shot('jornada-inicio-desktop.png');
// Fixture da primeira versão: a mesma chave, sem journey e com trabalhos existentes.
await evaluate(`window.__legacyFixture={version:1,completed:[0],records:{'m1-t1':{initial:{answer:'antiga',correct:false,time:1},revisions:[{answer:'revisada',correct:true,time:2}],resolved:true,guided:false}},applications:{0:'Aplicação anterior'},examAttempts:[{variant:0,answers:[0,0,0,0,0,0,0,0],results:[true,false,true,false,true,false,true,false],time:3}],composition:['C4','E4','G4','C5'].map(Music.parse),reflection:'Criação anterior',preferences:{volume:.18,narration:false,text:'1',reduced:false,teacher:false}};window.addEventListener('pagehide',()=>localStorage.setItem('missoes-musicais-v1',JSON.stringify(window.__legacyFixture)),{once:true});`);
async function reloadReady(selector){await cdp('Page.reload');for(let n=0;n<80;n++){if(await evaluate(`!!document.querySelector(${JSON.stringify(selector)})`))break;await delay(100);}}
await reloadReady('[data-action="resume-mission"]');
await check('Compatibilidade com progresso v1 sem apagar trabalhos',`Progress.state.completed[0]===0&&Progress.state.records['m1-t1'].initial.correct===false&&Progress.state.records['m1-t1'].revisions.length===1&&Progress.state.applications[0]==='Aplicação anterior'&&Progress.state.composition.length===4&&Progress.state.examAttempts.length===1&&Progress.state.preferences.volume===.18&&!!Progress.state.journey`);
await click('#reset');await check('Reinício confirmado em perfil isolado',`Progress.state.completed.length===0&&Progress.state.composition.length===0`);
await click('[data-action="enter"]');await click('[data-action="map"]');await click('[data-mission="0"]');
await check('Uma etapa por tela e foco no título',`document.querySelectorAll('.current-step').length===1&&document.querySelector('.current-step').dataset.step==='0'&&!document.querySelector('#piano-host')&&document.activeElement===document.querySelector('#screen-title')&&document.querySelector('#stage-announcement').textContent.includes('Cena de apresentação')`);
await click('[data-action="step-next"]');await check('Demonstração, exemplo resolvido e piano',`document.querySelector('.current-step').dataset.step==='1'&&document.querySelectorAll('.key').length===25&&document.querySelector('.demonstration').textContent.includes('Exemplo resolvido')`);
await evaluate(`document.querySelector('#reduce-motion').checked=true;document.querySelector('#reduce-motion').dispatchEvent(new Event('change'))`);await click('[data-action="animate-names"]');await check('Animação de nomes inclusivos',`document.querySelector('#animation-output').textContent.includes('NOMES: 1/8')`);await click('[data-action="step-animation"]');await check('Avanço manual da animação',`document.querySelector('#animation-output').textContent.includes('NOMES: 2/8')`);await click('[data-action="animate-chromatic"]');await check('Semitons começam em zero',`document.querySelector('#animation-output').textContent.includes('DISTÂNCIA: 0 de 12')`);
await selectPair(['G4','C5']);await click('[data-action="step-next"]');await selectPair(['E4','F4']);await click('[data-action="step-back"]');await check('Voltar preserva seleção da demonstração',`document.querySelector('[data-slot="0"] span').textContent==='sol4'&&document.querySelector('[data-slot="1"] span').textContent==='dó5'`);await click('[data-action="step-next"]');await check('Continuar preserva seleção do experimento',`document.querySelector('[data-slot="0"] span').textContent==='mi4'&&document.querySelector('[data-slot="1"] span').textContent==='fá4'`);
await reloadReady('[data-step="2"]');await check('Retoma etapa e notas após recarregar',`document.querySelector('[data-step="2"]')&&document.querySelector('[data-slot="0"] span').textContent==='mi4'&&document.activeElement===document.querySelector('#screen-title')`);
await click('[data-action="step-next"]');await selectPair(['C4','D4']);await check('Seleção não revela solução no desafio',`document.querySelector('#analysis').textContent===''&&document.querySelector('[data-piano="investigate"]').disabled`);await click('[data-action="check-piano"]');await check('Enunciado, instrumento e feedback na mesma área',`document.querySelector('.challenge-workspace #task-feedback')&&document.querySelector('.challenge-workspace #piano-host')&&Progress.state.records['m1-t1'].initial.correct===false`);await click('[data-action="hint"]');await click('[data-action="step-back"]');await click('[data-action="step-next"]');await check('Voltar preserva erro, piano e pista',`Progress.state.journey.hints['m1-t1']===1&&document.querySelector('#hints').textContent.includes('Observe')&&document.querySelector('[data-slot="1"] span').textContent==='ré4'`);await click('[data-action="hint"]');await click('[data-action="hint"]');await click('[data-action="guided-demo"]');await click('[data-action="guided-complete"]');await check('Inicial, pistas e revisão guiada separados; sem avanço automático',`Progress.state.records['m1-t1'].initial.correct===false&&Progress.state.records['m1-t1'].initial.hintsUsed===0&&Progress.state.records['m1-t1'].revisions.at(-1).hintsUsed===3&&Progress.state.records['m1-t1'].guided&&Progress.state.journey.hintEvents['m1-t1'].length===3&&document.querySelector('[data-step="3"]')`);await shot('jornada-desafio-desktop.png');
await click('[data-action="step-next"]');const correct1=await evaluate('Missions[0].tasks[1].correct');await click(`[name="answer"][value="${correct1}"]`);await click('[data-action="step-back"]');await click('[data-action="step-next"]');await check('Alternativa ainda não enviada persiste ao voltar',`document.querySelector('[name="answer"]:checked').value===String(${correct1})&&!Progress.state.records['m1-t2']`);await reloadReady('[data-step="4"]');await check('Retoma rascunho de alternativa após recarregar',`document.querySelector('[name="answer"]:checked').value===String(${correct1})`);
await check('Questão conceitual oferece apoio fechado sem foco oculto',`document.querySelector('#support-area').hidden&&!document.querySelector('.key')&&document.querySelector('[data-action="toggle-support"]')&&!document.querySelector('[hidden] :focus')`);await click('[data-action="toggle-support"]');await selectPair(['C4','C5']);await click('[data-action="toggle-support"]');await check('Fechar apoio remove instrumento da navegação',`document.querySelector('#support-area').hidden&&document.querySelector('[data-action="toggle-support"]').getAttribute('aria-expanded')==='false'`);await click('[data-action="toggle-support"]');await check('Reabrir apoio conserva notas',`document.querySelector('[data-slot="1"] span').textContent==='dó5'`);
const wrong1=(correct1+1)%5;await click(`[name="answer"][value="${wrong1}"]`);await evaluate(`document.querySelector('#task-form').requestSubmit()`);await click(`[name="answer"][value="${correct1}"]`);await evaluate(`document.querySelector('#task-form').requestSubmit()`);await check('Correção não substitui resposta inicial',`Progress.state.records['m1-t2'].initial.correct===false&&Progress.state.records['m1-t2'].revisions.at(-1).correct===true`);
for(let m=0;m<6;m++){
 if(m>0){await click('[data-action="next-mission"]');await click('[data-action="step-next"]');await click('[data-action="step-next"]');await click('[data-action="step-next"]');}
 for(let t=m===0?2:0;t<4;t++){
  if(m===0||t>0)await click('[data-action="step-next"]');
  const data=await evaluate(`Missions[${m}].tasks[${t}]`);
  if(data.type==='piano'){await selectPair(data.pair);await click('[data-action="check-piano"]');}else{await click(`[name="answer"][value="${data.correct}"]`);await evaluate(`document.querySelector('#task-form').requestSubmit()`);}
  await check(`Missão ${m+1}, desafio ${t+1} em tela própria`, `Progress.state.records['m${m+1}-t${t+1}'].resolved&&document.querySelector('.current-step').dataset.step==='${t+3}'&&document.querySelectorAll('.task-prompt').length===1`);
 }
 await click('[data-action="step-next"]');await evaluate(`document.querySelector('#application-text').value='Nono ano: nomes inclusivos e semitons separados.';document.querySelector('#application-text').dispatchEvent(new Event('input',{bubbles:true}))`);await click('[data-action="step-back"]');await click('[data-action="step-next"]');await check(`Rascunho criativo da missão ${m+1} preservado`, `document.querySelector('#application-text').value.includes('nomes inclusivos')`);await click('[data-action="save-application"]');
 if(m===5)break;
 await click('[data-action="step-next"]');await click('[data-action="complete"]');await check(`Conquista ${m+1} sem avanço automático e próxima missão`, `Progress.state.completed.includes(${m})&&document.querySelector('[data-step="8"]')&&document.querySelector('[data-action="revisit"]')&&document.querySelector('[data-action="next-mission"]')`);
}
await click('[data-action="step-next"]');await check('Conclusão mostra o que falta na missão final',`document.querySelector('.missing-list').textContent.includes('prova')&&document.querySelector('.missing-list').textContent.includes('criação')`);await click('[data-action="step-back"]');await click('[data-action="exam"]');await check('Questão conceitual da prova sem piano não planejado',`!document.querySelector('[data-action="exam-support"]')&&!document.querySelector('#piano-host')&&!document.querySelector('.exam').textContent.includes('Correta:')`);await click('[data-action="exam-finish"]');await check('Entrega incompleta continua bloqueada',`Progress.state.examAttempts.length===0&&document.querySelector('#notice').textContent.includes('oito')`);
await click('[data-exam-index="1"]');await click('[data-action="exam-support"]');await selectPair(['E4','F4']);await check('Apoio planejado da prova não classifica ou demonstra solução',`document.querySelector('[data-piano="investigate"]').disabled&&!document.querySelector('[data-action="guided-demo"]')&&document.querySelector('#analysis').textContent===''`);await click('[data-exam-index="0"]');await click('[data-exam-index="1"]');await check('Apoio e seleção da prova preservados por questão',`document.querySelector('[data-slot="0"] span').textContent==='mi4'&&document.querySelector('[data-slot="1"] span').textContent==='fá4'`);
for(let i=0;i<8;i++){await click(`[data-exam-index="${i}"]`);const answer=await evaluate(`(ExamSets[0][${i}].correct-${i}%5+5)%5`);await click(`[name="exam-answer"][value="${answer}"]`);}
await reloadReady('#exam-form');await check('Retomada da prova, página e respostas',`Progress.state.examDraft.index===7&&document.querySelector('#exam-form [type="radio"]:checked')&&Progress.state.examDraft.answers.every(a=>a!==null)`);await click('[data-exam-index="0"]');await click('[name="exam-answer"][value="1"]');await click('[name="exam-answer"][value="0"]');await click('[data-action="exam-finish"]');await check('Correção só após entrega e desempenho por conceito',`Progress.state.examAttempts[0].results.every(Boolean)&&document.querySelectorAll('.concept-grid>div').length===8&&document.querySelector('h1').textContent.startsWith('8/8')`);await click('[data-action="exam-new"]');await check('Nova prova mantém anterior e varia questões',`Progress.state.examDraft.variant===1&&Progress.state.examAttempts.length===1&&document.querySelector('.task-prompt').textContent.includes('lá4')`);await click('[data-action="return-final"]');await click('[data-action="composer"]');await click('[data-resource="2"]');await check('Recurso de composição preservado',`Progress.state.composition.length===2`);await click('[data-action="clear-composition"]');await click('[data-action="record-toggle"]');for(const n of [60,63,67,72])await click(`[data-midi="${n}"]`);await click('[data-action="record-toggle"]');await evaluate(`document.querySelector('#reflection').value='Terças e quintas para sugerir expectativa.';document.querySelector('#reflection').dispatchEvent(new Event('input'))`);await click('[data-action="save-composition"]');await click('[data-sequence="0"]');await click('[data-sequence="2"]');await check('Composição e análise preservadas',`Progress.state.composition.length===4&&document.querySelector('#composition-analysis').textContent.includes('quinta justa')`);await click('[data-action="play-composition"]');await reloadReady('#reflection');await check('Retomada da criação com notas e intenção',`Progress.state.composition.length===4&&document.querySelector('#reflection').value.includes('expectativa')&&document.querySelector('[data-slot="1"] span').textContent==='sol4'`);
await cdp('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:out});await click('[data-action="export"]');const exported=path.join(out,'minha-sequencia-musical.json');for(let n=0;n<80&&!fs.existsSync(exported);n++)await delay(100);assert.ok(fs.existsSync(exported));assert.equal(JSON.parse(fs.readFileSync(exported,'utf8')).notes.length,4);checks.push('Exportação real de composição JSON');await click('[data-action="clear-composition"]');await fileInput(exported);await check('Importação real restaura a criação',`Progress.state.composition.length===4&&Progress.state.reflection.includes('expectativa')`);const different=path.join(out,'criacao-alterada.json'),differentData=JSON.parse(fs.readFileSync(exported,'utf8'));differentData.reflection='Intenção importada diferente';differentData.notes[1]={letter:'F',alteration:1,octave:4};fs.writeFileSync(different,JSON.stringify(differentData));await fileInput(different);await check('Importação não é sobrescrita pelo rascunho anterior',`Progress.state.reflection==='Intenção importada diferente'&&document.querySelector('#reflection').value==='Intenção importada diferente'&&Progress.state.composition[1].letter==='F'`);
const invalid=path.join(out,'invalido.json');fs.writeFileSync(invalid,'{"version":1,"notes":[]}');await fileInput(invalid);await check('JSON inválido não substitui criação',`Progress.state.composition.length===4&&document.querySelector('#notice').textContent.includes('recusada')`);
await click('[data-action="return-final"]');await click('[data-action="step-next"]');await click('[data-action="complete"]');await check('Seis missões concluídas com criação e prova',`Progress.state.completed.length===6&&document.querySelector('[data-step="8"]')`);await click('[data-action="revisit"]');await check('Revisitar começa a cena sem apagar registros',`document.querySelector('[data-step="0"]')&&Progress.state.completed.length===6&&Progress.state.composition.length===4`);
await click('#map-button');await click('[data-action="free"]');await selectPair(['C4','F#4']);await click('[data-piano="investigate"]');await check('Cálculo mantém quarta aumentada',`document.querySelector('#analysis').textContent.includes('quarta aumentada')`);await change('#spelling','flat');await selectPair(['C4','Gb4']);await click('[data-piano="investigate"]');await check('Mesma altura mantém quinta diminuta pela grafia',`document.querySelector('#analysis').textContent.includes('quinta diminuta')`);await selectPair(['G4','C4']);await click('[data-piano="investigate"]');await check('Descida continua orientada sem classificação incorreta',`document.querySelector('#analysis').textContent.includes('descendente')`);await click('[data-piano="clear"]');await evaluate(`document.querySelector('h1').focus()`);await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'a',code:'KeyA',text:'a'});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'a',code:'KeyA'});await check('Atalho do piano continua ativo',`document.querySelector('[data-slot="0"] span').textContent==='dó4'`);
await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await change('#text-size','1.3');await check('Celular com texto ampliado sem transbordar a página',`document.documentElement.scrollWidth<=window.innerWidth`);await click('#map-button');await click('[data-mission="4"]');await click('[data-action="revisit"]');await click('[data-action="step-next"]');await check('Demonstração móvel mantém leitura e teclas acessíveis',`document.documentElement.scrollWidth<=window.innerWidth&&document.querySelectorAll('.key').length===25&&getComputedStyle(document.querySelector('.piano-scroll')).overflowX==='auto'`);await shot('jornada-demonstracao-celular.png');await click('[data-action="animate-enharmonic"]');await click('[data-action="step-animation"]');await check('Animação enarmônica preservada',`document.querySelector('#animation-output').textContent.includes('quinta diminuta')&&document.querySelector('[data-slot="1"] span').textContent==='sol♭4'`);await click('[data-action="step-next"]');await click('[data-action="step-next"]');await check('Ordem móvel coloca piano entre enunciado e resposta',`document.querySelector('#task-content').children[0].className==='task-question'&&document.querySelector('#task-content').children[1].id==='support-area'&&document.querySelector('#task-content').children[2].className==='task-answer'`);await check('Teclado ampliado mantém rótulos e acesso à última tecla',`document.querySelector('.keyboard').scrollWidth>=1040&&document.querySelector('[data-midi="84"]')`);await check('Desafio móvel ampliado sem corte ou barra sobreposta',`document.documentElement.scrollWidth<=window.innerWidth&&getComputedStyle(document.querySelector('#notice')).position==='static'&&getComputedStyle(document.querySelector('#sound-dock')).position==='static'&&getComputedStyle(document.querySelector('body')).overflowY!=='hidden'`);await shot('jornada-desafio-celular.png');
await click('#map-button');await click('[data-mission="5"]');for(let n=0;n<7;n++)await click('[data-action="step-next"]');await click('[data-action="composer"]');await click('#reset');await check('Reinício não recupera rascunhos da tela anterior',`Progress.state.reflection===''&&Progress.state.composition.length===0&&Object.keys(Progress.state.journey.drafts).length===0`);await click('#map-button');await evaluate(`document.querySelector('#teacher').checked=true;document.querySelector('#teacher').dispatchEvent(new Event('change'))`);await check('Modo professor continua liberando todas as missões',`[...document.querySelectorAll('[data-mission]')].every(b=>!b.disabled)`);await evaluate(`Object.defineProperty(Storage.prototype,'setItem',{value(){throw new Error('bloqueio simulado')}});Progress.save()`);await check('Falha de persistência mantém interface utilizável',`Progress.storageOK===false&&document.querySelector('#notice').textContent.includes('não pôde salvar')`);
assert.deepEqual(errors,[],'Console sem erros');checks.push('Console sem exceções ou erros');fs.writeFileSync(path.join(out,'journey-report.json'),JSON.stringify({date:new Date().toISOString(),checks,errors,audio:'APIs acionadas; escuta humana pendente.'},null,2));console.log(`TOTAL: ${checks.length} verificações no Edge, console limpo.`);
}catch(e){console.error(e);if(ws)try{await shot('jornada-falha.png');console.error('PAGE:',await evaluate('document.body.innerText.slice(0,6500)'));}catch{}process.exitCode=1;}finally{if(ws&&ws.readyState===WebSocket.OPEN)try{await cdp('Browser.close');}catch{}clearInterval(keepalive);if(ws)ws.close();child.kill();}})();
